[project]
name = "lc-pymupdf"
version = "0.1.0"
description = "A langchain's PyMuPDFLoader implementation to load PDF files"
requires-python = ">=3.13"
dependencies = [
    "langchain-community>=0.3.19",
    "langchain-core>=0.3.43",
    "pymupdf>=1.25.3",
    "rich>=13.9.4",
    "tqdm>=4.67.1",
]
